import { Room } from "../types";

export const barRoom: Room = {
    id: "bar",
    group: "gikopoi",
    scale: 1,
    size: { x: 9, y: 9 },
    originCoordinates: { x: 0, y: 352 },
    spawnPoint: "right",
    backgroundImageUrl: "rooms/bar/background.svg",
    objects: [
        { x: 2, y: 1, offset: { x: 130, y: 311 }, url: "table.svg" },
        { x: 2, y: 2, offset: { x: 170, y: 291 }, url: "table.svg" },
        { x: 6, y: 1, offset: { x: 290, y: 391 }, url: "table.svg" },
        { x: 6, y: 2, offset: { x: 330, y: 370 }, url: "table.svg" },
        
        { x: 2, y: 7, offset: { x: 372, y: 184 }, url: "counter_left.svg" },
        { x: 2, y: 6, offset: { x: 332, y: 204 }, url: "counter_left.svg" },
        { x: 2, y: 5, offset: { x: 315, y: 224 }, url: "counter_bottom_left.svg" },
        { x: 3, y: 5, offset: { x: 319, y: 244 }, url: "counter_bottom.svg" },
        { x: 4, y: 5, offset: { x: 359, y: 264 }, url: "counter_bottom.svg" },
        { x: 5, y: 5, offset: { x: 399, y: 284 }, url: "counter_bottom.svg" },
        { x: 6, y: 5, offset: { x: 440, y: 299 }, url: "counter_bottom_right.svg" },
        { x: 6, y: 6, offset: { x: 477, y: 279 }, url: "counter_right.svg" },
        { x: 6, y: 7, offset: { x: 517, y: 259 }, url: "counter_right.svg" },
        
        { x: 1, y: 8, offset: { x: 372, y:  86 }, url: "shelves.svg" },
        
        { x: 0, y: 0, offset: { x:  45, y: 183 }, url: "light.svg" },
        { x: 0, y: 2, offset: { x: 125, y: 143 }, url: "light.svg" },
        { x: 0, y: 4, offset: { x: 204, y: 103 }, url: "light.svg" },
    ],
    sit: [
        { x: 1, y: 1 },
        { x: 1, y: 2 },
        { x: 3, y: 1 },
        { x: 3, y: 2 },
        { x: 5, y: 1 },
        { x: 5, y: 2 },
        { x: 7, y: 1 },
        { x: 7, y: 2 },
        { x: 1, y: 5 },
        { x: 1, y: 6 },
        { x: 1, y: 7 },
        { x: 2, y: 4 },
        { x: 3, y: 4 },
        { x: 4, y: 4 },
        { x: 5, y: 4 },
        { x: 6, y: 4 },
        { x: 7, y: 5 },
        { x: 7, y: 6 },
        { x: 7, y: 7 }
    ],
    blocked: [
        { x: 2, y: 1 },
        { x: 2, y: 2 },
        { x: 6, y: 1 },
        { x: 6, y: 2 },
        { x: 2, y: 5 },
        { x: 3, y: 5 },
        { x: 4, y: 5 },
        { x: 5, y: 5 },
        { x: 6, y: 5 },
        { x: 2, y: 6 },
        { x: 2, y: 7 },
        { x: 6, y: 6 },
        { x: 6, y: 7 },
        { x: 1, y: 8 },
        { x: 2, y: 8 },
        { x: 3, y: 8 },
        { x: 4, y: 8 },
        { x: 5, y: 8 },
        { x: 6, y: 8 },
        { x: 7, y: 8 },
    ],
    forbiddenMovements: [],
    doors: {
        right: { x: 8, y: 4, direction: "left", target: { roomId: "bar_st", doorId: "bar" } },
        ladder: { x: 0, y: 0, direction: "right", target: { roomId: "bar_st", doorId: "bar_roof" } },
        hatch: { x: 3, y: 7, direction: "down", target: { roomId: "basement", doorId: "left" } }
    },
    streamSlotCount: 2,
}