import { Room } from "../types";

export const barGikoSquareRoom: Room = {
    id: "bar_giko_square",
    group: "bar_giko",
    scale: 1,
    size: { x: 24, y: 22 },
    originCoordinates: { x: -160, y: 505 },
    spawnPoint: "up",
    backgroundImageUrl: "rooms/bar_giko_square/background.svg",
    objects: [
        { x:  3, y:  8, offset: { x:    0, y:  160 }, url: "koban.svg" },
        { x: 15, y: 18, offset: { x: 1160, y:  220 }, url: "bar_giko.svg" },
        { x: 16, y: 17, offset: { x: 1168, y:  394 }, url: "bar_giko_sign.svg" },
        { x: 12, y: 10, offset: { x:  660, y:  383 }, url: "fountain.svg" },
        { x:  5, y: 17, offset: { x:  766, y:  195 }, url: "bench.svg" },
        { x: 19, y:  4, offset: { x:  790, y:  546 }, url: "street_light_left.svg" },
        { x: 14, y: 17, offset: { x: 1110, y:  186 }, url: "street_light_left.svg" },
        { x:  9, y:  4, offset: { x:  390, y:  346 }, url: "street_light_right.svg" },
        { x: 0, y: 11, offset: { x: 344 , y: 707 }, url: "arrow-down.svg" },
    ],
    sit: [
        { x:  6, y: 17 },
        { x:  7, y: 17 },
        { x:  8, y: 17 },
        // fountain
        { x: 13, y: 10 },
        { x: 13, y: 11 },
        { x: 11, y:  9 },
        { x: 12, y:  9 },
    ],
    blocked: [
        // Koban quarter
        { x:  8, y:  0 },
        { x:  8, y:  1 },
        { x:  8, y:  2 },
        { x:  8, y:  3 },
        { x:  7, y:  3 },
        { x:  6, y:  3 },
        { x:  5, y:  3 },
        { x:  4, y:  3 },
        { x:  3, y:  4 },
        { x:  3, y:  5 },
        { x:  3, y:  6 },
        { x:  3, y:  7 },
        { x:  3, y:  8 },
        { x:  2, y:  8 },
        { x:  1, y:  8 },
        { x:  0, y:  8 },
        
        // Yoshinoya quarter
        { x:  0, y:  13 },
        { x:  1, y:  13 },
        { x:  2, y:  13 },
        { x:  3, y:  13 },
        { x:  3, y:  14 },
        { x:  3, y:  15 },
        { x:  3, y:  16 },
        { x:  3, y:  17 },
        { x:  4, y:  18 },
        { x:  5, y:  18 },
        { x:  6, y:  18 },
        { x:  7, y:  18 },
        { x:  8, y:  18 },
        { x:  8, y:  19 },
        { x:  8, y:  20 },
        { x:  8, y:  21 },
        
        // Bar Giko quarter
        { x:  15, y:  21 },
        { x:  15, y:  20 },
        { x:  15, y:  19 },
        { x:  15, y:  18 },
        { x:  17, y:  18 },
        { x:  18, y:  18 },
        { x:  19, y:  18 },
        { x:  20, y:  17 },
        { x:  20, y:  16 },
        { x:  20, y:  15 },
        { x:  20, y:  14 },
        { x:  20, y:  13 },
        { x:  21, y:  13 },
        { x:  22, y:  13 },
        { x:  23, y:  13 },
        
        // Bar Giko sign
        { x:  16, y:  17 },
        
        // Empty quarter
        { x:  23, y:  8 },
        { x:  22, y:  8 },
        { x:  21, y:  8 },
        { x:  20, y:  8 },
        { x:  20, y:  7 },
        { x:  20, y:  6 },
        { x:  20, y:  5 },
        { x:  18, y:  3 },
        { x:  17, y:  3 },
        { x:  16, y:  3 },
        { x:  15, y:  3 },
        { x:  15, y:  2 },
        { x:  15, y:  1 },
        { x:  15, y:  0 },
        
        // Street lights
        { x:  9, y:  4 },
        { x: 14, y: 17 },
        { x: 19, y:  4 },
        
        // Fountain
        { x: 12, y: 12 },
        { x: 12, y: 11 },
        { x: 12, y: 10 },
        { x: 11, y: 12 },
        { x: 10, y: 11 },
        { x: 10, y: 10 },
        { x: 11, y: 10 },
    ],
    forbiddenMovements: [],
    doors: {
        up: { x: 11, y: 21, direction: "down", target: { roomId: "densha", doorId: "left_middle" } },
        bar_giko: { x: 17, y: 17, direction: "down", target: { roomId: "bar_giko", doorId: "stairs" } },
        yoshinoya: { x: 4, y: 15, direction: "right", target: { roomId: "yoshinoya", doorId: "door" } },
        left: { x: 0, y: 12, direction: "right", target: { roomId: "monachat", doorId: "door" } },
        right: { x: 23, y: 11, direction: "left", target: { roomId: "konbini", doorId: "door" } },
        office: { x: 5, y: 17, direction: "down", target: { roomId: "nerd_office", doorId: "door"} },
        very_left: { x: 9, y: 0, direction: "right", target: { roomId: "kyougijou", doorId: "door"} },
        next_to_light: { x: 18, y: 4, direction: "up", target: { roomId: "yojouhan", doorId: "door"} },
        bottom_left: {x: 12, y: 0, direction: "up", target: {roomId: "meganeya", doorId: "top_right"} },
        big_dicks: {x: 19, y: 15, direction: "left", target: {roomId: "karaoke_box", doorId: "door"} },
    },
    streamSlotCount: 3,
    games: ["janken"],
}