import { Room } from "../types.js";

export const kaidanRoom: Room = {
    id: "kaidan",
    group: "gikopoi",
    scale: 1,
    size: { x: 6, y: 11 },
    originCoordinates: { x: 725, y: 1153 },
    blockWidth: 40,
    blockHeight: 60,
    spawnPoint: "spawn",
    backgroundImageUrl: "rooms/kaidan/background.svg",
    objects: [],
    sit: [],
    blocked: [
        { x:  2, y: 10 },
        { x:  2, y:  9 },
        { x:  2, y:  8 },
        { x:  2, y:  7 },
        { x:  2, y:  6 },
        { x:  2, y:  5 },
        { x:  2, y:  4 },
        { x:  2, y:  3 },
        { x:  2, y:  2 },
        { x:  2, y:  1 },
        
        { x:  3, y: 10 },
        { x:  3, y:  9 },
        { x:  3, y:  8 },
        { x:  3, y:  7 },
        { x:  3, y:  6 },
        { x:  3, y:  5 },
        { x:  3, y:  4 },
        { x:  3, y:  3 },
        { x:  3, y:  2 },
        { x:  3, y:  1 },
    ],
    forbiddenMovements: [],
    doors: {
        spawn: { x: 0, y: 0, direction: "up", target: null },
        bottom_left: { x: 0, y: 0, direction: "right", target: { roomId: "admin_st", doorId: "right" } },
        bottom_right: { x: 4, y: 0, direction: "right", target: { roomId: "cafe_st", doorId: "top_right" } },
        top_left: { x: 0, y: 10, direction: "down", target: { roomId: "takadai", doorId: "left" } },
        top_right: { x: 4, y: 10, direction: "down", target: { roomId: "takadai", doorId: "right" } },
    },
    streamSlotCount: 0,
}