import { Room } from "../types";

export const schoolInternationalRoom: Room = {
    id: "school_international",
    group: "gikopoi",
    scale: 1,
    size: { x: 9, y: 12 },
    originCoordinates: { x: 0, y: 412 },
    spawnPoint: "right",
    backgroundImageUrl: "rooms/school_international/background.svg",
    objects: [
        { x:  1, y:  1, offset: { x:  134, y:  321 }, url: 'chair_back.svg' },
        { x:  1, y:  2, offset: { x:  136, y:  343 }, url: 'chair_base.svg' },
        { x:  1, y:  3, offset: { x:  161, y:  306 }, url: 'desk.svg' },
        { x:  1, y:  4, offset: { x:  254, y:  261 }, url: 'chair_back.svg' },
        { x:  1, y:  5, offset: { x:  256, y:  283 }, url: 'chair_base.svg' },
        { x:  1, y:  6, offset: { x:  281, y:  246 }, url: 'desk.svg' },
        { x:  1, y:  7, offset: { x:  374, y:  201 }, url: 'chair_back.svg' },
        { x:  1, y:  8, offset: { x:  376, y:  223 }, url: 'chair_base.svg' },
        { x:  1, y:  9, offset: { x:  401, y:  186 }, url: 'desk.svg' },
        { x:  3, y:  1, offset: { x:  214, y:  361 }, url: 'chair_back.svg' },
        { x:  3, y:  2, offset: { x:  216, y:  383 }, url: 'chair_base.svg' },
        { x:  3, y:  3, offset: { x:  241, y:  346 }, url: 'desk.svg' },
        { x:  3, y:  4, offset: { x:  334, y:  301 }, url: 'chair_back.svg' },
        { x:  3, y:  5, offset: { x:  336, y:  323 }, url: 'chair_base.svg' },
        { x:  3, y:  6, offset: { x:  361, y:  286 }, url: 'desk.svg' },
        { x:  3, y:  7, offset: { x:  454, y:  241 }, url: 'chair_back.svg' },
        { x:  3, y:  8, offset: { x:  456, y:  263 }, url: 'chair_base.svg' },
        { x:  3, y:  9, offset: { x:  481, y:  226 }, url: 'desk.svg' },
        { x:  5, y:  1, offset: { x:  294, y:  401 }, url: 'chair_back.svg' },
        { x:  5, y:  2, offset: { x:  296, y:  423 }, url: 'chair_base.svg' },
        { x:  5, y:  3, offset: { x:  321, y:  386 }, url: 'desk.svg' },
        { x:  5, y:  4, offset: { x:  414, y:  341 }, url: 'chair_back.svg' },
        { x:  5, y:  5, offset: { x:  416, y:  363 }, url: 'chair_base.svg' },
        { x:  5, y:  6, offset: { x:  441, y:  326 }, url: 'desk.svg' },
        { x:  5, y:  7, offset: { x:  534, y:  281 }, url: 'chair_back.svg' },
        { x:  5, y:  8, offset: { x:  536, y:  303 }, url: 'chair_base.svg' },
        { x:  5, y:  9, offset: { x:  561, y:  266 }, url: 'desk.svg' },
        { x:  7, y:  1, offset: { x:  374, y:  441 }, url: 'chair_back.svg' },
        { x:  7, y:  2, offset: { x:  376, y:  463 }, url: 'chair_base.svg' },
        { x:  7, y:  3, offset: { x:  401, y:  426 }, url: 'desk.svg' },
        { x:  7, y:  4, offset: { x:  494, y:  381 }, url: 'chair_back.svg' },
        { x:  7, y:  5, offset: { x:  496, y:  403 }, url: 'chair_base.svg' },
        { x:  7, y:  6, offset: { x:  521, y:  366 }, url: 'desk.svg' },
        { x:  7, y:  7, offset: { x:  614, y:  321 }, url: 'chair_back.svg' },
        { x:  7, y:  8, offset: { x:  616, y:  343 }, url: 'chair_base.svg' },
        { x:  7, y:  9, offset: { x:  641, y:  306 }, url: 'desk.svg' },
    ],
    sit: [
        { x:  1, y:  2 },
        { x:  3, y:  2 },
        { x:  5, y:  2 },
        { x:  7, y:  2 },
        { x:  1, y:  5 },
        { x:  3, y:  5 },
        { x:  5, y:  5 },
        { x:  7, y:  5 },
        { x:  1, y:  8 },
        { x:  3, y:  8 },
        { x:  5, y:  8 },
        { x:  7, y:  8 },
    ],
    blocked: [
        { x:  1, y:  3 },
        { x:  3, y:  3 },
        { x:  5, y:  3 },
        { x:  7, y:  3 },
        { x:  1, y:  6 },
        { x:  3, y:  6 },
        { x:  5, y:  6 },
        { x:  7, y:  6 },
        { x:  1, y:  9 },
        { x:  3, y:  9 },
        { x:  5, y:  9 },
        { x:  7, y:  9 },
    
        { x:  0, y: 11 },
    ],
    forbiddenMovements: [
        { xFrom:  1, yFrom:  2, xTo:  1, yTo:  1 }, { xFrom:  1, yFrom:  1, xTo:  1, yTo:  2 },
        { xFrom:  3, yFrom:  2, xTo:  3, yTo:  1 }, { xFrom:  3, yFrom:  1, xTo:  3, yTo:  2 },
        { xFrom:  5, yFrom:  2, xTo:  5, yTo:  1 }, { xFrom:  5, yFrom:  1, xTo:  5, yTo:  2 },
        { xFrom:  7, yFrom:  2, xTo:  7, yTo:  1 }, { xFrom:  7, yFrom:  1, xTo:  7, yTo:  2 },
        
        { xFrom:  1, yFrom:  5, xTo:  1, yTo:  4 }, { xFrom:  1, yFrom:  4, xTo:  1, yTo:  5 },
        { xFrom:  3, yFrom:  5, xTo:  3, yTo:  4 }, { xFrom:  3, yFrom:  4, xTo:  3, yTo:  5 },
        { xFrom:  5, yFrom:  5, xTo:  5, yTo:  4 }, { xFrom:  5, yFrom:  4, xTo:  5, yTo:  5 },
        { xFrom:  7, yFrom:  5, xTo:  7, yTo:  4 }, { xFrom:  7, yFrom:  4, xTo:  7, yTo:  5 },
        
        { xFrom:  1, yFrom:  8, xTo:  1, yTo:  7 }, { xFrom:  1, yFrom:  7, xTo:  1, yTo:  8 },
        { xFrom:  3, yFrom:  8, xTo:  3, yTo:  7 }, { xFrom:  3, yFrom:  7, xTo:  3, yTo:  8 },
        { xFrom:  5, yFrom:  8, xTo:  5, yTo:  7 }, { xFrom:  5, yFrom:  7, xTo:  5, yTo:  8 },
        { xFrom:  7, yFrom:  8, xTo:  7, yTo:  7 }, { xFrom:  7, yFrom:  7, xTo:  7, yTo:  8 },
    ],
    doors: {
        right: { x: 8, y: 1, direction: "left", target: { roomId: "school_rouka", doorId: "door_left" } },
    },
    streamSlotCount: 3,
}