import { Room } from "../types";

export const schoolRoom: Room = {
    id: "school",
    group: "gikopoi",
    scale: 1,
    size: { x: 8, y: 7 },
    originCoordinates: { x: 0, y: 312 },
    spawnPoint: "right",
    backgroundImageUrl: "rooms/school/background.svg",
    objects: [
        { x:  1, y:  1, offset: { x:   89, y:  242 }, url: 'desk.svg' },
        { x:  2, y:  1, offset: { x:  137, y:  283 }, url: 'seat_base.svg' },
        { x:  3, y:  1, offset: { x:  156, y:  262 }, url: 'seat_back.svg' },
        { x:  3, y:  1, offset: { x:  169, y:  282 }, url: 'desk.svg' },
        { x:  4, y:  1, offset: { x:  217, y:  323 }, url: 'seat_base.svg' },
        { x:  5, y:  1, offset: { x:  236, y:  302 }, url: 'seat_back.svg' },
        { x:  5, y:  1, offset: { x:  249, y:  322 }, url: 'desk.svg' },
        { x:  6, y:  1, offset: { x:  297, y:  363 }, url: 'seat_base.svg' },
        { x:  7, y:  1, offset: { x:  316, y:  342 }, url: 'seat_back.svg' },
        { x:  1, y:  3, offset: { x:  169, y:  202 }, url: 'desk.svg' },
        { x:  2, y:  3, offset: { x:  217, y:  243 }, url: 'seat_base.svg' },
        { x:  3, y:  3, offset: { x:  236, y:  222 }, url: 'seat_back.svg' },
        { x:  3, y:  3, offset: { x:  249, y:  242 }, url: 'desk.svg' },
        { x:  4, y:  3, offset: { x:  297, y:  283 }, url: 'seat_base.svg' },
        { x:  5, y:  3, offset: { x:  316, y:  262 }, url: 'seat_back.svg' },
        { x:  5, y:  3, offset: { x:  329, y:  282 }, url: 'desk.svg' },
        { x:  6, y:  3, offset: { x:  377, y:  323 }, url: 'seat_base.svg' },
        { x:  7, y:  3, offset: { x:  396, y:  302 }, url: 'seat_back.svg' },
        { x:  1, y:  5, offset: { x:  249, y:  162 }, url: 'desk.svg' },
        { x:  2, y:  5, offset: { x:  297, y:  203 }, url: 'seat_base.svg' },
        { x:  3, y:  5, offset: { x:  316, y:  182 }, url: 'seat_back.svg' },
        { x:  3, y:  5, offset: { x:  329, y:  202 }, url: 'desk.svg' },
        { x:  4, y:  5, offset: { x:  376, y:  243 }, url: 'seat_base.svg' },
        { x:  5, y:  5, offset: { x:  396, y:  222 }, url: 'seat_back.svg' },
        { x:  5, y:  5, offset: { x:  409, y:  242 }, url: 'desk_with_ika.svg' },
        { x:  6, y:  5, offset: { x:  457, y:  283 }, url: 'seat_base.svg' },
        { x:  7, y:  5, offset: { x:  476, y:  262 }, url: 'seat_back.svg' },
    ],
    sit: [
        { x:  2, y:  1 },
        { x:  2, y:  3 },
        { x:  2, y:  5 },
        { x:  4, y:  1 },
        { x:  4, y:  3 },
        { x:  4, y:  5 },
        { x:  6, y:  1 },
        { x:  6, y:  3 },
        { x:  6, y:  5 },
    ],
    blocked: [
        { x:  1, y:  1 },
        { x:  1, y:  3 },
        { x:  1, y:  5 },
        { x:  3, y:  1 },
        { x:  3, y:  3 },
        { x:  3, y:  5 },
        { x:  5, y:  1 },
        { x:  5, y:  3 },
        { x:  5, y:  5 },
    ],
    forbiddenMovements: [
        { xFrom:  6, yFrom:  1, xTo:  7, yTo:  1 }, { xFrom:  7, yFrom:  1, xTo:  6, yTo:  1 },
        { xFrom:  6, yFrom:  3, xTo:  7, yTo:  3 }, { xFrom:  7, yFrom:  3, xTo:  6, yTo:  3 },
        { xFrom:  6, yFrom:  5, xTo:  7, yTo:  5 }, { xFrom:  7, yFrom:  5, xTo:  6, yTo:  5 },
    ],
    doors: {
        right: { x: 7, y: 2, direction: "left", target: { roomId: "school_rouka", doorId: "door_right" } },
    },
    streamSlotCount: 0,
}