import { Room } from "../types.js";

export const schoolPcRoom: Room = {
    id: "school_pc",
    group: "gikopoi",
    scale: 1,
    size: { x: 9, y: 12 },
    originCoordinates: { x: 1, y: 412 },
    spawnPoint: "door",
    backgroundImageUrl: "rooms/school_pc/background.svg",
    objects: [
        { x:  1, y:  2, offset: { x:  149, y:  352 }, url: 'stool.svg' },
        { x:  1, y:  3, offset: { x:  161, y:  286 }, url: 'desk.svg' },
        { x:  1, y:  5, offset: { x:  269, y:  292 }, url: 'stool.svg' },
        { x:  1, y:  6, offset: { x:  281, y:  226 }, url: 'desk.svg' },
        { x:  1, y:  8, offset: { x:  389, y:  232 }, url: 'stool.svg' },
        { x:  1, y:  9, offset: { x:  401, y:  167 }, url: 'desk.svg' },
        { x:  3, y:  2, offset: { x:  229, y:  392 }, url: 'stool.svg' },
        { x:  3, y:  3, offset: { x:  241, y:  326 }, url: 'desk.svg' },
        { x:  3, y:  5, offset: { x:  348, y:  332 }, url: 'stool.svg' },
        { x:  3, y:  6, offset: { x:  361, y:  267 }, url: 'desk.svg' },
        { x:  3, y:  8, offset: { x:  469, y:  272 }, url: 'stool.svg' },
        { x:  3, y:  9, offset: { x:  481, y:  207 }, url: 'desk.svg' },
        { x:  5, y:  2, offset: { x:  309, y:  432 }, url: 'stool.svg' },
        { x:  5, y:  3, offset: { x:  321, y:  366 }, url: 'desk.svg' },
        { x:  5, y:  5, offset: { x:  428, y:  372 }, url: 'stool.svg' },
        { x:  5, y:  6, offset: { x:  441, y:  306 }, url: 'desk.svg' },
        { x:  5, y:  8, offset: { x:  548, y:  312 }, url: 'stool.svg' },
        { x:  5, y:  9, offset: { x:  561, y:  247 }, url: 'desk.svg' },
        { x:  7, y:  2, offset: { x:  388, y:  472 }, url: 'stool.svg' },
        { x:  7, y:  3, offset: { x:  401, y:  406 }, url: 'desk.svg' },
        { x:  7, y:  5, offset: { x:  508, y:  412 }, url: 'stool.svg' },
        { x:  7, y:  6, offset: { x:  521, y:  347 }, url: 'desk.svg' },
        { x:  7, y:  8, offset: { x:  628, y:  352 }, url: 'stool.svg' },
        { x:  7, y:  9, offset: { x:  641, y:  287 }, url: 'desk.svg' },
    ],
    sit: [
        { x:  1, y:  2 },
        { x:  1, y:  5 },
        { x:  1, y:  8 },
        { x:  3, y:  2 },
        { x:  3, y:  5 },
        { x:  3, y:  8 },
        { x:  5, y:  2 },
        { x:  5, y:  5 },
        { x:  5, y:  8 },
        { x:  7, y:  2 },
        { x:  7, y:  5 },
        { x:  7, y:  8 },
    ],
    blocked: [
        { x:  1, y:  3 },
        { x:  1, y:  6 },
        { x:  1, y:  9 },
        { x:  3, y:  3 },
        { x:  3, y:  6 },
        { x:  3, y:  9 },
        { x:  5, y:  3 },
        { x:  5, y:  6 },
        { x:  5, y:  9 },
        { x:  7, y:  3 },
        { x:  7, y:  6 },
        { x:  7, y:  9 },
    ],
    forbiddenMovements: [],
    doors: {
        door: { x: 0, y: 1, direction: "right", target: { roomId: "school_rouka", doorId: "right_bottom" } },
    },
    streamSlotCount: 1,
}