import { Room } from "../types";

export const seashoreRoom: Room = {
    id: "seashore",
    group: "gikopoi",
    scale: 1,
    size: { x: 9, y: 14 },
    originCoordinates: { x: 507, y: 556 },
    blockWidth: 80,
    blockHeight: 15,
    spawnPoint: "right",
    backgroundImageUrl: "rooms/seashore/background.svg",
    onlyDrawOverBackgroundImage: true,
    objects: [
        { x:  2, y:  6, offset: { x:  851, y:  486 }, url: 'seat.svg' },
        { x:  2, y:  7, offset: { x:  890, y:  479 }, url: 'seat.svg' },
        { x:  2, y:  8, offset: { x:  931, y:  471 }, url: 'seat.svg' },
        { x:  2, y:  9, offset: { x:  971, y:  464 }, url: 'seat.svg' },
        { x:  2, y: 10, offset: { x: 1011, y:  456 }, url: 'seat.svg' },
        { x:  2, y: 11, offset: { x: 1051, y:  449 }, url: 'seat.svg' },
        
        { x:  6, y:  6, offset: { x: 1011, y:  516 }, url: 'seat.svg' },
        { x:  6, y:  7, offset: { x: 1051, y:  509 }, url: 'seat.svg' },
        { x:  6, y:  8, offset: { x: 1091, y:  501 }, url: 'seat.svg' },
        { x:  6, y:  9, offset: { x: 1131, y:  494 }, url: 'seat.svg' },
        { x:  6, y: 10, offset: { x: 1171, y:  486 }, url: 'seat.svg' },
        { x:  6, y: 11, offset: { x: 1211, y:  479 }, url: 'seat.svg' },
    ],
    sit: [
        { x:  2, y:  6 },
        { x:  2, y:  7 },
        { x:  2, y:  8 },
        { x:  2, y:  9 },
        { x:  2, y: 10 },
        { x:  2, y: 11 },
        
        { x:  6, y:  6 },
        { x:  6, y:  7 },
        { x:  6, y:  8 },
        { x:  6, y:  9 },
        { x:  6, y: 10 },
        { x:  6, y: 11 },
    ],
    blocked: [],
    forbiddenMovements: [],
    doors: {
        right: { x: 8, y: 9, direction: "left", target: { roomId: "busstop", doorId: "left" } },
    },
    streamSlotCount: 0,
}